# Dockerfile for building the stack

#See https://appsody.dev/docs/stacks/environment-variables for more information about each variable.

ENV APPSODY_MOUNTS="~/.m2/repository:/mvn/repository;src:/project/user-app/src;pom.xml:/project/user-app/pom.xml;config.toml:/project/user-app/config.toml"

ENV APPSODY_WATCH_DIR=/project/user-app
ENV APPSODY_WATCH_IGNORE_DIR=/project/user-app/target
ENV APPSODY_WATCH_REGEX="^.*(.sol|.java)$"

ENV APPSODY_INSTALL="mvn -B -Dmaven.repo.local=/mvn/repository install -DskipTests && (target/besu-1.3.4/bin/besu --config-file=config.toml > logfile.log 2>&1 &) && ( tail -f -n0 logfile.log & ) | grep -q 'Ethereum main loop is up'"

ENV APPSODY_RUN="mvn -B -Dmaven.repo.local=/mvn/repository exec:java -Dexec.mainClass='com.sample.App'"
ENV APPSODY_RUN_ON_CHANGE="mvn -B -Dmaven.repo.local=/mvn/repository compile exec:java -Dexec.mainClass="com.sample.App""
ENV APPSODY_RUN_KILL=false

ENV APPSODY_DEBUG= #Command executed in 'debug' mode
ENV APPSODY_DEBUG_ON_CHANGE= #Command executed in 'debug' mode when a change is detected.
ENV APPSODY_DEBUG_KILL= #Signals whether to kill the server process before starting the ON_CHANGE action.

ENV APPSODY_TEST= #Command executed in 'test' mode
ENV APPSODY_TEST_ON_CHANGE= #Command executed in 'test' mode when a change is detected.
ENV APPSODY_TEST_KILL= #Signals whether to kill the server process before starting the ON_CHANGE action.
